### ISSUE TITLE
I get following error when I try to run it

### ISSUE THREAD

**Issue by yjeong73** [maxosprojects/cozmo-blockly#4]
[Server] Starting server...
Traceback (most recent call last):
  File "server.py", line 234, in <module>
    main()
  File "server.py", line 231, in main
    CozmoBlockly.start(args)
  File "server.py", line 199, in start
    tornado.platform.asyncio.AsyncIOMainLoop().install()
AttributeError: module 'tornado.platform' has no attribute 'asyncio'
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'xmldom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jacobkim/School/Fall2018/Learning from Demonstration/Cozmo/cozmo-blockly/nodejs/headless.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by jacob-hanbeen-kim** [comment]
> [Server] Starting server...
> Traceback (most recent call last):
> File "server.py", line 234, in 
> main()
> File "server.py", line 231, in main
> CozmoBlockly.start(args)
> File "server.py", line 199, in start
> tornado.platform.asyncio.AsyncIOMainLoop().install()
> AttributeError: module 'tornado.platform' has no attribute 'asyncio'
> internal/modules/cjs/loader.js:596
> throw err;
> ^
> 
> Error: Cannot find module 'xmldom'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
> at Function.Module._load (internal/modules/cjs/loader.js:520:25)
> at Module.require (internal/modules/cjs/loader.js:650:17)
> at require (internal/modules/cjs/helpers.js:20:18)
> at Object. (/Users/jacobkim/School/Fall2018/Learning from Demonstration/Cozmo/cozmo-blockly/nodejs/headless.js:3:20)
> at Module._compile (internal/modules/cjs/loader.js:702:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
> at Module.load (internal/modules/cjs/loader.js:612:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
> at Function.Module._load (internal/modules/cjs/loader.js:543:3)

nvm. Needed to install npm install in the nodejs folder

**Comment by maxosprojects** [comment]
Closing since it's been resolved
